apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fabedgeOperator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "fabedgeOperator.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fabedgeOperator.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.operator.name }}
          image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - --namespace={{ .Release.Namespace }}
            - --edge-pod-cidr={{ .Values.operator.edgePodCIDR }}
            - --cni-type={{ .Values.cniType }}
            - --agent-image={{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}
            - --agent-strongswan-image={{ .Values.strongswan.image.repository }}:{{ .Values.strongswan.image.tag | default .Chart.AppVersion }}
            - --connector-config=connector-config
            - --edge-labels={{ .Values.operator.edgeLabels }}
            - --connector-public-addresses={{ .Values.operator.connectorPublicAddresses }}
            - --connector-subnets={{ .Values.operator.connectorSubnets }}
            - --endpoint-id-format=C=CN, O=fabedge.io, CN={node}
            - --agent-masq-outgoing={{ .Values.operator.masqOutgoing }}
            - --agent-enable-proxy={{ .Values.operator.enableProxy }}
            - -v=5
          {{- if .Values.operator.resources }}
          resources:
{{ toYaml .Values.operator.resources | indent 12 }}
          {{- end }}
      hostNetwork: true
      serviceAccountName: {{ .Values.operator.name }}
      {{- if .Values.operator.affinity }}
      affinity:
{{ toYaml .Values.operator.affinity | indent 8 }}
      {{- end }}
