graph TD
    A[cmdADD] --> B{检查是否有网桥?};
    B -->|无| C[根据配置创建网桥];
    B --> |有| D;
    C --> D[在容器netns创建veth pair];
    D --> E[关联host veth与网桥]
    E --> F{检查本地IP是否足够}
    F --> |是| G[获取一个IP地址]
    F --> |否| H[向云端申请IP段]
    H --> G
    G --> i[为container veth配置IP]
    i --> j[发起ARP广播]
    j --> Z[结束];
