apiVersion: v2
name: fabedge
version: 0.0.1
type: application
description: FabEdge is an open source edge networking solution based on kubernetes and kubeedge. 
home: https://www.fabedge.io
sources:
  - https://github.com/FabEdge/fabedge
keywords:
  - fabedge
  - network
  - edge
maintainers: 
  - name: fabedge
    email: fabedge@beyondcent.com
appVersion: "v0.2.beta"
