apiVersion: v1
kind: Service
metadata:
  name: operator
spec:
  selector:
    app: fabedge-operator
  type: NodePort
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30303
