name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - platforms: linux/amd64
          tags: fabedge/installer
          file: build/installer/Dockerfile

        - platforms: linux/amd64,linux/arm64
          tags: fabedge/strongswan
          file: build/strongswan/Dockerfile

        - platforms: linux/amd64,linux/arm64
          tags: fabedge/connector
          file: build/connector/Dockerfile

        - platforms: linux/amd64,linux/arm64
          tags: fabedge/operator
          file: build/operator/Dockerfile

        - platforms: linux/amd64,linux/arm64
          tags: fabedge/agent
          file: build/agent/Dockerfile

        - platforms: linux/amd64,linux/arm64
          tags: fabedge/cert
          file: build/cert/Dockerfile

    steps:
    - uses: actions/checkout@v2

    - name: Remove proxies
      run: |
        bash build/utils/no_proxy.sh

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ matrix.platforms }}
        push: true
        tags: ${{ matrix.tags }}
        file: ${{ matrix.file }}
